### PR TITLE
[RELEASE-1.0] 

### PR DESCRIPTION
**Pull request by alex-stout**
This PR represents the release of 1.0 of the Parking Notifier. The front-end and API are up to the standards of a release. During this first release, the SMS notifications will be sent out manually. Automation of the process will be introduced in later versions.

### Changelog:
- Totally revamped frontend
- Form validation
- API creates & deletes users
- Notification is integrated with database
- Scraping of city website streamlined & hardened
- Email verification is implemented to ensure only valid UWEC emails are provided

### CODE REVIEW

**Review by katherine-reiter — DISMISSED** [review]
I believe notify.js will need to be changed to get the numbers from the number controller, since there is no longer a user.phone field

**Comment by TMisch** [comment]
Yup, I've been working on updating notify.js to be able to actually read in the users correctly. My goal is to have it done for our meeting this afternoon. We won't be able to manually trigger the twilio sends until notify.js has been updated.

**Review by taylor-misch — DISMISSED** [review]
Like Katherine said, notify.js is not ready for launch quite yet. I'm working on updates now and hope to have them done by the end of today. As far as I can tell, notify.js is not pulling the users from the endpoint. Without a populated users array, the twilio service will not be able to send the message to everyone that is signed up. So we wouldn't even be able to trigger it manually. "Manually" would have to become going through each number and firing it off from twilio by hand. 

I'm working on changes now to get notify.js up to date. If I can get that done than I think version 1.0 would be ready for release.

**Comment by alex-stout** [comment]
@katherine-reiter & @TMisch thanks for the info! Must've missed that in my changes. Thank you!

**Review by taylor-misch — DISMISSED** [review]
Everything looks ready to go. I'm going to approve this, but we should comment out the notifyHelper(app) line in monitor.js so we can send out the message manually still.

**Pull request merged**
